WebDriver
RenzO102/test pull request #5
Opened 2022-10-20 09:47 UTC by RenzO102

2022-10-20 09:50 UTC, kurau commented on pom.xml
> +            <artifactId>selenium-server</artifactId>
А зачем сервер?

2022-10-20 09:51 UTC, kurau commented on pom.xml
> +            <scope>test</scope>
Можно один раз оставить без теста и всё

2022-10-20 09:51 UTC, kurau commented on src/test/java/ru/github/com/RenzO102/HelpDesk/HelpTest.java
> +                String password = "Omon9751";
Спасибо за пароль

2022-10-20 09:54 UTC, kurau commented on src/test/java/ru/github/com/RenzO102/HelpDesk/MainPage.java
> +    private WebElement nextnbutton;
CamelCase
nextButton

2022-10-20 09:55 UTC, kurau commented on src/test/java/ru/github/com/RenzO102/HelpDesk/MainPage.java
> +    private WebElement loginpass;
pass тут что значит?

2022-10-20 09:56 UTC, kurau commented on src/test/java/ru/github/com/RenzO102/HelpDesk/MainPage.java
> +    private WebElement button;
там пол сайта button`ов
у тебя подсказка в локаторе, как её назвать - submit

2022-10-20 09:56 UTC, kurau commented on src/test/java/ru/github/com/RenzO102/HelpDesk/MainPage.java
> +        driver.get("https://account.mail.ru/login?page=https%3A%2F%2Fe.mail.ru%2Fmessages%2Finbox&allow_external=1");
Owner

2022-10-20 09:56 UTC, kurau commented on src/test/java/ru/github/com/RenzO102/HelpDesk/HelpTest.java
> +                String email = "stson102@mail.ru";
owner

2022-10-20 09:57 UTC, kurau commented on src/test/java/ru/github/com/RenzO102/SeleniumPage.java
> +   protected static WebDriver driver;
Точно статик?

2022-10-20 09:57 UTC, kurau commented on src/test/java/ru/github/com/RenzO102/SeleniumPage.java
> +   protected static WebDriver driver;
Это в примере так?

2022-10-20 09:57 UTC, kurau commented on src/test/java/ru/github/com/RenzO102/WebTest.java
> +
Где тест?

2022-10-20 09:58 UTC, kurau commented on src/test/java/ru/github/com/RenzO102/WebTest.java
> +       // driver.quit();
Не надо закрывать драйвер?

2022-10-20 18:18 UTC, RenzO102 commented on src/test/java/ru/github/com/RenzO102/SeleniumPage.java
> +   protected static WebDriver driver;
да в примере

2022-10-20 18:18 UTC, RenzO102 commented on src/test/java/ru/github/com/RenzO102/WebTest.java
> +
Оишбочно

2022-10-20 18:18 UTC, RenzO102 commented on src/test/java/ru/github/com/RenzO102/WebTest.java
> +       // driver.quit();
закрыл

2022-10-20 18:18 UTC, RenzO102 commented on src/test/java/ru/github/com/RenzO102/WebTest.java
> +
Ошибочно

2022-10-20 18:18 UTC, RenzO102 commented on src/test/java/ru/github/com/RenzO102/HelpDesk/MainPage.java
> +    private WebElement loginpass;
Не нужен

2022-10-20 18:19 UTC, RenzO102 commented on src/test/java/ru/github/com/RenzO102/HelpDesk/MainPage.java
> +    private WebElement nextnbutton;
Вот это не пойму

2022-10-20 18:19 UTC, RenzO102 commented on pom.xml
> +            <scope>test</scope>
Ок

2022-10-20 18:19 UTC, RenzO102 commented on pom.xml
> +            <artifactId>selenium-server</artifactId>
В примере было так

2022-10-21 06:29 UTC, kurau requested changes

2022-10-21 07:00 UTC, RenzO102 commented on src/test/java/ru/github/com/RenzO102/HelpDesk/HelpTest.java
> +    public void checkTicket() {
Точно точно

2022-10-29 05:14 UTC, merged